dinivas:
  production: false
  workspace:
    root-path: '/Users/chidi/.dinivas/workspace'
  orm:
    config:
      type: postgres
      host: localhost
      port: 5433
      username: dinivas
      password: Pa55W0rd
      database: dinivas
      synchronize: true
      logging: false
  terraform:
    min_required_version: '0.12.2'
    debug_command_outputs: false
    state:
      username: dinivas
      password: Pa55w0rd!
    modules:
      - name: project_base
        type: git
        provider: openstack
        url: https://github.com/dinivas/terraform-openstack-project-base.git
      - name: jenkins
        type: git
        provider: openstack
        url: https://github.com/dinivas/terraform-openstack-jenkins.git
      - name: consul
        type: git
        provider: openstack
        url: https://github.com/dinivas/terraform-openstack-consul.git
      - name: keypair
        type: git
        provider: openstack
        url: https://github.com/dinivas/terraform-openstack-keypair.git
      - name: rabbitmq
        type: git
        provider: openstack
        url: https://github.com/dinivas/terraform-openstack-rabbitmq.git
      - name: flavor
        type: git
        provider: openstack
        url: https://github.com/dinivas/terraform-openstack-flavor.git
  packer:
    modules:
      - name: base_image
        type: git
        url: https://github.com/dinivas/packer-dinivas-base-image.git
      - name: proxy
        type: git
        url: https://github.com/dinivas/packer-dinivas-proxy.git
      - name: jenkins
        type: git
        url: https://github.com/dinivas/packer-jenkins.git
      - name: docker
        type: git
        url: https://github.com/dinivas/packer-dinivas-docker.git
      - name: rabbitmq
        type: git
        url: https://github.com/dinivas/packer-dinivas-rabbitmq.git
  ansible_galaxy:
    url: http://localhost:8089
  keycloak:
    config:
      realm: 'dinivas'
      bearer-only: true
      auth-server-url: 'http://localhost:8085/auth'
      ssl-required: 'external'
      resource: 'dinivas-api'
      verify-token-audience: true
      credentials:
        secret: 'c7629cf6-cd8a-465f-8f08-97af5781bb7f'
      confidential-port: 0
      policy-enforcer:
    admin:
      username: admin
      password: password
